//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunCat.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunCat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat_0 {
            get {
                object obj = ResourceManager.GetObject("dark_cat_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat_1 {
            get {
                object obj = ResourceManager.GetObject("dark_cat_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat_2 {
            get {
                object obj = ResourceManager.GetObject("dark_cat_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat_3 {
            get {
                object obj = ResourceManager.GetObject("dark_cat_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat_4 {
            get {
                object obj = ResourceManager.GetObject("dark_cat_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_0 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_1 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_2 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_3 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_4 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_5 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_6 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_7 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_8 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_parrot_9 {
            get {
                object obj = ResourceManager.GetObject("dark_parrot_9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_cat_0 {
            get {
                object obj = ResourceManager.GetObject("light_cat_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_cat_1 {
            get {
                object obj = ResourceManager.GetObject("light_cat_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_cat_2 {
            get {
                object obj = ResourceManager.GetObject("light_cat_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_cat_3 {
            get {
                object obj = ResourceManager.GetObject("light_cat_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_cat_4 {
            get {
                object obj = ResourceManager.GetObject("light_cat_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_0 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_1 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_2 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_3 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_4 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_5 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_6 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_7 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_8 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_parrot_9 {
            get {
                object obj = ResourceManager.GetObject("light_parrot_9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

///////////////////////////////////////////////////////////////

        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_0 {
            get {
                object obj = ResourceManager.GetObject("light_flower_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_1 {
            get {
                object obj = ResourceManager.GetObject("light_flower_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_2 {
            get {
                object obj = ResourceManager.GetObject("light_flower_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_3 {
            get {
                object obj = ResourceManager.GetObject("light_flower_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_4 {
            get {
                object obj = ResourceManager.GetObject("light_flower_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_5 {
            get {
                object obj = ResourceManager.GetObject("light_flower_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_6 {
            get {
                object obj = ResourceManager.GetObject("light_flower_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_7 {
            get {
                object obj = ResourceManager.GetObject("light_flower_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_8 {
            get {
                object obj = ResourceManager.GetObject("light_flower_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_flower_9 {
            get {
                object obj = ResourceManager.GetObject("light_flower_9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_0 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_1 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_2 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_3 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_4 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_5 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_6 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_7 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_8 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_flower_9 {
            get {
                object obj = ResourceManager.GetObject("dark_flower_9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
////////////////////////////////////////////////////////////////////////
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_kickstone_0 {
            get {
                object obj = ResourceManager.GetObject("dark_kickstone_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_kickstone_1 {
            get {
                object obj = ResourceManager.GetObject("dark_kickstone_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_kickstone_2 {
            get {
                object obj = ResourceManager.GetObject("dark_kickstone_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_kickstone_3 {
            get {
                object obj = ResourceManager.GetObject("dark_kickstone_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_kickstone_4 {
            get {
                object obj = ResourceManager.GetObject("dark_kickstone_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_kickstone_0 {
            get {
                object obj = ResourceManager.GetObject("light_kickstone_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_kickstone_1 {
            get {
                object obj = ResourceManager.GetObject("light_kickstone_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_kickstone_2 {
            get {
                object obj = ResourceManager.GetObject("light_kickstone_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_kickstone_3 {
            get {
                object obj = ResourceManager.GetObject("light_kickstone_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon light_kickstone_4 {
            get {
                object obj = ResourceManager.GetObject("light_kickstone_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
//////////////////////////////////////////////////////////////////////
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_0 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_1 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_2 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_3 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_4 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_5 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_6 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_7 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_8 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_9 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_10 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_11 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_cat2_12 {
            get {
                object obj = ResourceManager.GetObject("dark_car2_12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        //////////////////////////////
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_0 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_1 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_2 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_3 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_4 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_5 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_6 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_7 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_8 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_9 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_10 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_11 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        

        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_12 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_13 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_13", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_14 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_14", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_15 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_15", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_16 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_17 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_17", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_18 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_18", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_19 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_19", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_20 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_20", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_21 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_21", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_22 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_22", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_23 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_23", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_24 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_colorfulcat_25 {
            get {
                object obj = ResourceManager.GetObject("dark_colorfulcat_25", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
/////////////////////////////////////////////////
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_hios_0 {
            get {
                object obj = ResourceManager.GetObject("dark_hios_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_hios_1 {
            get {
                object obj = ResourceManager.GetObject("dark_hios_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_hios_2 {
            get {
                object obj = ResourceManager.GetObject("dark_hios_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
//////////////////////////////////////////
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_0 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_1 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_2 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_3 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_4 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_5 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_6 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_7 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dark_slime_8 {
            get {
                object obj = ResourceManager.GetObject("dark_slime_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

    }
}
